spring:
  profile: 
    active:
      - dev
--- 

server:
  port: 9201
  

feign: 
  hystrix: 
    enabled: true

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://localhost:9101/eureka/   
      #defaultZone: http://localhost:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  