spring:
  profile: 
    active:
      - dev
--- 

server:
  port: 9301
  
#需要开启feign  面向接口的方式添加 对服务降级的支持 fallback 字段  映射了对应的接口类实现的 fallbackfactory 接口 并且引入了maven  feign的jar包  
feign: 
  hystrix: 
    enabled: true

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://localhost:7001/eureka/   
      #defaultZone: http://localhost:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  
